server:
    port: 8081

spring:
    application:
        name: web
#    datasource:
#        schema:
management:
    endpoints:
        web:
            exposure:
                include: "*"
    endpoint:
        health:
            show-details: ALWAYS

foo:
    name: foo